//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.Site1;

[assembly: RegisterDocumentType(SampleBasicRoute.CLASS_NAME, typeof(SampleBasicRoute))]

namespace CMS.DocumentEngine.Types.Site1
{
	/// <summary>
	/// Represents a content item of type SampleBasicRoute.
	/// </summary>
	public partial class SampleBasicRoute : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "Site1.SampleBasicRoute";


		/// <summary>
		/// The instance of the class that provides extended API for working with SampleBasicRoute fields.
		/// </summary>
		private readonly SampleBasicRouteFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// Gets an object that provides extended API for working with SampleBasicRoute fields.
		/// </summary>
		[RegisterProperty]
		public SampleBasicRouteFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with SampleBasicRoute fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class SampleBasicRouteFields : AbstractHierarchicalObject<SampleBasicRouteFields>
		{
			/// <summary>
			/// The content item of type SampleBasicRoute that is a target of the extended API.
			/// </summary>
			private readonly SampleBasicRoute mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="SampleBasicRouteFields" /> class with the specified content item of type SampleBasicRoute.
			/// </summary>
			/// <param name="instance">The content item of type SampleBasicRoute that is a target of the extended API.</param>
			public SampleBasicRouteFields(SampleBasicRoute instance)
			{
				mInstance = instance;
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="SampleBasicRoute" /> class.
		/// </summary>
		public SampleBasicRoute() : base(CLASS_NAME)
		{
			mFields = new SampleBasicRouteFields(this);
		}

		#endregion
	}
}